"""Initial professional structure

Revision ID: 0001
Revises: 
Create Date: 2026-04-14 16:44:29.624589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- BLOQUE SEGURO: Solo crea si no existen ---
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = 'approle' AND n.nspname = 'operations') THEN
                CREATE TYPE operations.approle AS ENUM ('ADMIN', 'USER', 'SUPERVISOR');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = 'messagerole' AND n.nspname = 'operations') THEN
                CREATE TYPE operations.messagerole AS ENUM ('USER', 'ASSISTANT');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = 'tipomovimiento' AND n.nspname = 'operations') THEN
                CREATE TYPE operations.tipomovimiento AS ENUM ('CONTEO', 'CONSUMO', 'MERMA');
            END IF;
        END $$;
    """)

    # ### commands auto generated by Alembic ###
    op.create_table('bodegas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('categorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('system_prompt', sa.String(length=2000), nullable=False),
    sa.Column('is_tts_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('selected_voice', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('recetas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('native_language', sa.String(length=50), server_default='Spanish', nullable=False),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False),
    sa.Column('user_image', sa.String(length=1048), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('has_accepted_terms', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'SUPERVISOR', name='approle', schema='operations', create_type=False), server_default='USER', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('username'),
    schema='operations'
    )
    op.create_index('idx_user_email_username', 'users', ['email', 'username'], unique=False, schema='operations')
    op.create_table('email_confirmation_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=1048), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='operations'
    )
    op.create_index('idx_email_confirmation_token_token', 'email_confirmation_tokens', ['token'], unique=False, schema='operations')
    op.create_table('eventos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('ejecutado', sa.Boolean(), nullable=False),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', name='messagerole', schema='operations', create_type=False), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['operations.chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    schema='operations'
    )
    op.create_index('idx_message_chat_id', 'messages', ['chat_id'], unique=False, schema='operations')
    op.create_index('idx_message_user_id', 'messages', ['user_id'], unique=False, schema='operations')
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='operations'
    )
    op.create_index('idx_reset_token_expires_at', 'password_reset_tokens', ['expires_at'], unique=False, schema='operations')
    op.create_index('idx_reset_token_token', 'password_reset_tokens', ['token'], unique=False, schema='operations')
    op.create_index('idx_reset_token_user_id', 'password_reset_tokens', ['user_id'], unique=False, schema='operations')
    op.create_table('permisos_merma',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otorgado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['otorgado_por'], ['operations.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('productos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['operations.categorias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('read_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['operations.chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='operations'
    )
    op.create_index('idx_refresh_token_expires_at', 'refresh_tokens', ['expires_at'], unique=False, schema='operations')
    op.create_index('idx_refresh_token_token', 'refresh_tokens', ['token'], unique=False, schema='operations')
    op.create_index('idx_refresh_token_user_id', 'refresh_tokens', ['user_id'], unique=False, schema='operations')
    op.create_table('user_chat',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['operations.chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id'),
    schema='operations'
    )
    op.create_table('user_session_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index('idx_session_login_time', 'user_session_history', ['login_time'], unique=False, schema='operations')
    op.create_index('idx_session_user_id', 'user_session_history', ['user_id'], unique=False, schema='operations')
    op.create_table('ventas_recetas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receta_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['operations.recetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('producto_bodegas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_id', sa.Uuid(), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['operations.bodegas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['operations.productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'bodega_id', name='uix_producto_bodega'),
    schema='operations'
    )
    op.create_table('receta_ingredientes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receta_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['operations.bodegas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['operations.productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receta_id'], ['operations.recetas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('registros_stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_movimiento', postgresql.ENUM('CONTEO', 'CONSUMO', 'MERMA', name='tipomovimiento', schema='operations', create_type=False), nullable=False),
    sa.Column('motivo_merma', sa.String(length=255), nullable=True),
    sa.Column('descripcion_merma', sa.String(length=500), nullable=True),
    sa.Column('fecha_recuento', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['operations.bodegas.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['operations.eventos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producto_id'], ['operations.productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_stock', schema='operations')
    op.drop_table('receta_ingredientes', schema='operations')
    op.drop_table('producto_bodegas', schema='operations')
    op.drop_table('ventas_recetas', schema='operations')
    op.drop_index('idx_session_user_id', table_name='user_session_history', schema='operations')
    op.drop_index('idx_session_login_time', table_name='user_session_history', schema='operations')
    op.drop_table('user_session_history', schema='operations')
    op.drop_table('user_chat', schema='operations')
    op.drop_index('idx_refresh_token_user_id', table_name='refresh_tokens', schema='operations')
    op.drop_index('idx_refresh_token_token', table_name='refresh_tokens', schema='operations')
    op.drop_index('idx_refresh_token_expires_at', table_name='refresh_tokens', schema='operations')
    op.drop_table('refresh_tokens', schema='operations')
    op.drop_table('read_status', schema='operations')
    op.drop_table('productos', schema='operations')
    op.drop_table('permisos_merma', schema='operations')
    op.drop_index('idx_reset_token_user_id', table_name='password_reset_tokens', schema='operations')
    op.drop_index('idx_reset_token_token', table_name='password_reset_tokens', schema='operations')
    op.drop_index('idx_reset_token_expires_at', table_name='password_reset_tokens', schema='operations')
    op.drop_table('password_reset_tokens', schema='operations')
    op.drop_index('idx_message_user_id', table_name='messages', schema='operations')
    op.drop_index('idx_message_chat_id', table_name='messages', schema='operations')
    op.drop_table('messages', schema='operations')
    op.drop_table('eventos', schema='operations')
    op.drop_index('idx_email_confirmation_token_token', table_name='email_confirmation_tokens', schema='operations')
    op.drop_table('email_confirmation_tokens', schema='operations')
    op.drop_index('idx_user_email_username', table_name='users', schema='operations')
    op.drop_table('users', schema='operations')
    op.drop_table('recetas', schema='operations')
    op.drop_table('chats', schema='operations')
    op.drop_table('categorias', schema='operations')
    op.drop_table('bodegas', schema='operations')
    op.execute("DROP TYPE operations.approle")
    op.execute("DROP TYPE operations.messagerole")
    op.execute("DROP TYPE operations.tipomovimiento")
    # ### end Alembic commands ###
