"""Configuración Restaurante y Roles

Revision ID: 0006
Revises: 0005
Create Date: 2026-04-17 17:52:15.309046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_restaurante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.add_column('recetas', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False), schema='operations')
    op.drop_constraint(op.f('ventas_recetas_receta_id_fkey'), 'ventas_recetas', schema='operations', type_='foreignkey')
    op.create_foreign_key(None, 'ventas_recetas', 'recetas', ['receta_id'], ['id'], source_schema='operations', referent_schema='operations', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas_recetas', schema='operations', type_='foreignkey')
    op.create_foreign_key(op.f('ventas_recetas_receta_id_fkey'), 'ventas_recetas', 'recetas', ['receta_id'], ['id'], source_schema='operations', referent_schema='operations', ondelete='CASCADE')
    op.drop_column('recetas', 'is_active', schema='operations')
    op.drop_table('configuracion_restaurante', schema='operations')
    # ### end Alembic commands ###
