"""Sync with original projec

Revision ID: 0008
Revises: 0007
Create Date: 2026-04-18 17:41:07.898520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_recetas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='operations'
    )
    op.create_table('compras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('factura_url', sa.String(length=1000), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('conteos_inventario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bodega_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['operations.bodegas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('permisos_gestion_usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otorgado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['otorgado_por'], ['operations.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='operations'
    )
    op.create_table('compra_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('compra_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_id', sa.Uuid(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['operations.bodegas.id'], ),
    sa.ForeignKeyConstraint(['compra_id'], ['operations.compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['operations.productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('conteo_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conteo_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_contada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conteo_id'], ['operations.conteos_inventario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['operations.productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('evento_recetas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evento_id', sa.Uuid(), nullable=False),
    sa.Column('receta_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['operations.eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receta_id'], ['operations.recetas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.add_column('producto_bodegas', sa.Column('coordenada_letra', sa.String(length=10), nullable=True), schema='operations')
    op.add_column('producto_bodegas', sa.Column('coordenada_numero', sa.String(length=10), nullable=True), schema='operations')
    op.add_column('productos', sa.Column('codigo_barra', sa.String(length=100), nullable=True), schema='operations')
    op.add_column('productos', sa.Column('factor_conversion', sa.Numeric(precision=10, scale=4), server_default=sa.text('1.0'), nullable=False), schema='operations')
    op.add_column('productos', sa.Column('unidad_conversion', sa.String(length=50), nullable=True), schema='operations')
    op.add_column('productos', sa.Column('imagen_url', sa.String(length=1000), nullable=True), schema='operations')
    op.add_column('productos', sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'), nullable=False), schema='operations')
    op.add_column('productos', sa.Column('marca', sa.String(length=100), nullable=True), schema='operations')
    op.add_column('productos', sa.Column('proveedor', sa.String(length=200), nullable=True), schema='operations')
    op.add_column('recetas', sa.Column('imagen_url', sa.String(length=1000), nullable=True), schema='operations')
    op.add_column('recetas', sa.Column('categoria_receta_id', sa.Uuid(), nullable=True), schema='operations')
    op.create_foreign_key(None, 'recetas', 'categorias_recetas', ['categoria_receta_id'], ['id'], source_schema='operations', referent_schema='operations', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recetas', schema='operations', type_='foreignkey')
    op.drop_column('recetas', 'categoria_receta_id', schema='operations')
    op.drop_column('recetas', 'imagen_url', schema='operations')
    op.drop_column('productos', 'proveedor', schema='operations')
    op.drop_column('productos', 'marca', schema='operations')
    op.drop_column('productos', 'precio_venta', schema='operations')
    op.drop_column('productos', 'imagen_url', schema='operations')
    op.drop_column('productos', 'unidad_conversion', schema='operations')
    op.drop_column('productos', 'factor_conversion', schema='operations')
    op.drop_column('productos', 'codigo_barra', schema='operations')
    op.drop_column('producto_bodegas', 'coordenada_numero', schema='operations')
    op.drop_column('producto_bodegas', 'coordenada_letra', schema='operations')
    op.drop_table('evento_recetas', schema='operations')
    op.drop_table('conteo_items', schema='operations')
    op.drop_table('compra_items', schema='operations')
    op.drop_table('permisos_gestion_usuarios', schema='operations')
    op.drop_table('conteos_inventario', schema='operations')
    op.drop_table('compras', schema='operations')
    op.drop_table('categorias_recetas', schema='operations')
    # ### end Alembic commands ###
