"""sincronizacion completa modelo producto

Revision ID: 0009
Revises: 0008
Create Date: 2026-04-21 16:40:55.689808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('iva_incluido', sa.Boolean(), server_default=sa.text('true'), nullable=False), schema='operations')
    op.add_column('productos', sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), server_default=sa.text('19.0'), nullable=False), schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'iva_porcentaje', schema='operations')
    op.drop_column('productos', 'iva_incluido', schema='operations')
    # ### end Alembic commands ###
