"""add_missing_tables_and_fields

Revision ID: 0010
Revises: 0009
Create Date: 2026-04-25 11:17:32.269238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos_gestion_productos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otorgado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['otorgado_por'], ['operations.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='operations'
    )
    op.create_table('permisos_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otorgado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['otorgado_por'], ['operations.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='operations'
    )
    op.create_table('sugerencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=2000), nullable=False),
    sa.Column('estado', sa.String(length=50), server_default='recibida', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('tickets_soporte',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=False),
    sa.Column('estado', sa.String(length=50), server_default='abierto', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.add_column('bodegas', sa.Column('icono', sa.String(length=50), nullable=True), schema='operations')
    op.add_column('compras', sa.Column('pedido_realizado', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='operations')
    op.add_column('configuracion_restaurante', sa.Column('dias_alerta_vencimiento', sa.Numeric(precision=5, scale=0), server_default=sa.text('5'), nullable=False), schema='operations')
    op.add_column('conteos_inventario', sa.Column('nombre', sa.String(length=200), nullable=True), schema='operations')
    op.add_column('recetas', sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), server_default=sa.text('19.0'), nullable=False), schema='operations')
    op.add_column('recetas', sa.Column('iva_incluido', sa.Boolean(), server_default=sa.text('true'), nullable=False), schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recetas', 'iva_incluido', schema='operations')
    op.drop_column('recetas', 'iva_porcentaje', schema='operations')
    op.drop_column('conteos_inventario', 'nombre', schema='operations')
    op.drop_column('configuracion_restaurante', 'dias_alerta_vencimiento', schema='operations')
    op.drop_column('compras', 'pedido_realizado', schema='operations')
    op.drop_column('bodegas', 'icono', schema='operations')
    op.drop_table('tickets_soporte', schema='operations')
    op.drop_table('sugerencias', schema='operations')
    op.drop_table('permisos_inventario', schema='operations')
    op.drop_table('permisos_gestion_productos', schema='operations')
    # ### end Alembic commands ###
