"""Add BI models: Proveedor relations, GastoOperativo, MotivoMerma Enum

Revision ID: 0013
Revises: 0012
Create Date: 2026-04-30 14:56:19.955353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos_operativos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_gasto', sa.Date(), nullable=False),
    sa.Column('es_fijo', sa.Boolean(), nullable=False),
    sa.Column('estado_pago', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    # Removed unintended drop statements
    op.add_column('compras', sa.Column('proveedor_id', sa.UUID(), nullable=True), schema='operations')
    op.alter_column('compras', 'factura_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True,
               schema='operations')
    op.drop_constraint(op.f('compras_usuario_id_fkey'), 'compras', schema='operations', type_='foreignkey')
    op.create_foreign_key(None, 'compras', 'proveedores', ['proveedor_id'], ['id'], source_schema='operations', referent_schema='operations', ondelete='SET NULL')
    op.drop_column('compras', 'proveedor', schema='operations')
    op.add_column('productos', sa.Column('proveedor_id', sa.UUID(), nullable=True), schema='operations')
    op.create_foreign_key(None, 'productos', 'proveedores', ['proveedor_id'], ['id'], source_schema='operations', referent_schema='operations', ondelete='SET NULL')
    op.drop_column('productos', 'proveedor', schema='operations')
    op.add_column('proveedores', sa.Column('categoria_principal', sa.String(length=100), nullable=True), schema='operations')
    op.add_column('proveedores', sa.Column('dias_plazo_pago', sa.Integer(), nullable=False), schema='operations')
    op.add_column('proveedores', sa.Column('tiempo_entrega_promedio_dias', sa.Integer(), nullable=True), schema='operations')
    op.add_column('proveedores', sa.Column('activo', sa.Boolean(), nullable=False), schema='operations')
    op.alter_column('proveedores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='operations')
    op.alter_column('proveedores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='operations')
    op.alter_column('proveedores', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='operations')
    op.drop_index(op.f('ix_proveedores_nombre_empresa'), table_name='proveedores', schema='operations')
    # Explicitly create the enum type
    motivo_merma_enum = postgresql.ENUM('vencimiento', 'daño', 'error', 'caducidad', 'exceso', 'mal estado', 'otro', name='motivo_merma_enum', schema='operations')
    motivo_merma_enum.create(op.get_bind())

    op.alter_column('registros_stock', 'motivo_merma',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('vencimiento', 'daño', 'error', 'caducidad', 'exceso', 'mal estado', 'otro', name='motivo_merma_enum', schema='operations'),
               postgresql_using='motivo_merma::operations.motivo_merma_enum',
               existing_nullable=True,
               schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros_stock', 'motivo_merma',
               existing_type=sa.Enum('vencimiento', 'daño', 'error', 'caducidad', 'exceso', 'mal estado', 'otro', name='motivo_merma_enum', schema='operations'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='operations')
    
    # Explicitly drop the enum type
    motivo_merma_enum = postgresql.ENUM('vencimiento', 'daño', 'error', 'caducidad', 'exceso', 'mal estado', 'otro', name='motivo_merma_enum', schema='operations')
    motivo_merma_enum.drop(op.get_bind())
    op.create_index(op.f('ix_proveedores_nombre_empresa'), 'proveedores', ['nombre_empresa'], unique=False, schema='operations')
    op.alter_column('proveedores', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='operations')
    op.alter_column('proveedores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='operations')
    op.alter_column('proveedores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='operations')
    op.drop_column('proveedores', 'activo', schema='operations')
    op.drop_column('proveedores', 'tiempo_entrega_promedio_dias', schema='operations')
    op.drop_column('proveedores', 'dias_plazo_pago', schema='operations')
    op.drop_column('proveedores', 'categoria_principal', schema='operations')
    op.add_column('productos', sa.Column('proveedor', sa.VARCHAR(length=200), autoincrement=False, nullable=True), schema='operations')
    op.drop_constraint(None, 'productos', schema='operations', type_='foreignkey')
    op.drop_column('productos', 'proveedor_id', schema='operations')
    op.add_column('compras', sa.Column('proveedor', sa.VARCHAR(length=200), autoincrement=False, nullable=True), schema='operations')
    op.drop_constraint(None, 'compras', schema='operations', type_='foreignkey')
    op.create_foreign_key(op.f('compras_usuario_id_fkey'), 'compras', 'users', ['usuario_id'], ['id'], source_schema='operations', referent_schema='operations')
    op.alter_column('compras', 'factura_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True,
               schema='operations')
    op.drop_column('compras', 'proveedor_id', schema='operations')
    # Removed unintended create statements
    op.drop_table('gastos_operativos', schema='operations')
    # ### end Alembic commands ###
