"""add_color_to_bodegas

Revision ID: 0014
Revises: 0013
Create Date: 2026-04-29 01:13:54.477889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento_productos')
    op.drop_table('evento_recetas')
    op.drop_table('eventos')
    op.add_column('bodegas', sa.Column('color', sa.String(length=20), server_default=sa.text("'#10B981'"), nullable=True), schema='operations')
    op.drop_constraint(op.f('compra_items_bodega_id_fkey'), 'compra_items', schema='operations', type_='foreignkey')
    op.drop_constraint(op.f('compra_items_producto_id_fkey'), 'compra_items', schema='operations', type_='foreignkey')
    op.alter_column('compras', 'factura_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True,
               schema='operations')
    op.alter_column('compras', 'proveedor',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='operations')
    op.drop_constraint(op.f('compras_usuario_id_fkey'), 'compras', schema='operations', type_='foreignkey')
    op.drop_column('evento_productos', 'is_deleted', schema='operations')
    op.drop_column('evento_recetas', 'is_deleted', schema='operations')
    op.drop_column('eventos', 'is_deleted', schema='operations')
    op.alter_column('proveedores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='operations')
    op.alter_column('proveedores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='operations')
    op.drop_index(op.f('ix_proveedores_nombre_empresa'), table_name='proveedores', schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_proveedores_nombre_empresa'), 'proveedores', ['nombre_empresa'], unique=False, schema='operations')
    op.alter_column('proveedores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='operations')
    op.alter_column('proveedores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='operations')
    op.add_column('eventos', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='operations')
    op.add_column('evento_recetas', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='operations')
    op.add_column('evento_productos', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='operations')
    op.create_foreign_key(op.f('compras_usuario_id_fkey'), 'compras', 'users', ['usuario_id'], ['id'], source_schema='operations', referent_schema='operations')
    op.alter_column('compras', 'proveedor',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True,
               schema='operations')
    op.alter_column('compras', 'factura_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True,
               schema='operations')
    op.create_foreign_key(op.f('compra_items_producto_id_fkey'), 'compra_items', 'productos', ['producto_id'], ['id'], source_schema='operations', referent_schema='operations')
    op.create_foreign_key(op.f('compra_items_bodega_id_fkey'), 'compra_items', 'bodegas', ['bodega_id'], ['id'], source_schema='operations', referent_schema='operations')
    op.drop_column('bodegas', 'color', schema='operations')
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ejecutado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('cancelado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_publico', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('eventos_pkey'))
    )
    op.create_table('evento_recetas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('evento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receta_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('evento_recetas_evento_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('evento_recetas_pkey'))
    )
    op.create_table('evento_productos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('evento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bodega_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('evento_productos_evento_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('evento_productos_pkey'))
    )
    # ### end Alembic commands ###
