"""add_sku_to_products

Revision ID: 0015
Revises: 0014
Create Date: 2026-04-29 01:57:13.728648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: Union[str, None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('sku', sa.String(length=100), nullable=True), schema='operations')
    op.create_unique_constraint(None, 'productos', ['sku'], schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', schema='operations', type_='unique')
    op.drop_column('productos', 'sku', schema='operations')
    # ### end Alembic commands ###
