"""add cantidad_pedida to compra_items

Revision ID: 0015
Revises: 0014
Create Date: 2026-04-30 19:31:02.121248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: Union[str, None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compra_items', sa.Column('cantidad_pedida', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False), schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('compra_items_bodega_id_fkey'), 'compra_items', 'bodegas', ['bodega_id'], ['id'], source_schema='operations', referent_schema='operations')
    op.create_foreign_key(op.f('compra_items_producto_id_fkey'), 'compra_items', 'productos', ['producto_id'], ['id'], source_schema='operations', referent_schema='operations')
    op.drop_column('compra_items', 'cantidad_pedida', schema='operations')
    op.create_table('evento_productos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('evento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bodega_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('evento_productos_evento_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('evento_productos_pkey'))
    )
    op.create_table('proveedores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('nombre_empresa', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nombre_contacto', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('proveedores_pkey'))
    )
    op.create_index(op.f('ix_proveedores_nombre_empresa'), 'proveedores', ['nombre_empresa'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ejecutado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('cancelado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_publico', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('eventos_pkey'))
    )
    op.create_table('evento_recetas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('evento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receta_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('evento_recetas_evento_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('evento_recetas_pkey'))
    )
    # ### end Alembic commands ###
