"""add_reversion_redo_to_tipomovimiento

Revision ID: 0018
Revises: 0017
Create Date: 2026-04-30 08:19:05.931434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas', sa.Column('titulo', sa.String(length=200), nullable=True), schema='operations')
    op.add_column('notas', sa.Column('fecha', sa.DateTime(timezone=True), nullable=True), schema='operations')
    # ### end Alembic commands ###
    
    # Enum updates (Alembic autogenerate doesn't catch these automatically)
    op.execute("ALTER TYPE operations.tipomovimiento ADD VALUE IF NOT EXISTS 'reversion'")
    op.execute("ALTER TYPE operations.tipomovimiento ADD VALUE IF NOT EXISTS 'redo'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas', 'fecha', schema='operations')
    op.drop_column('notas', 'titulo', schema='operations')
    # ### end Alembic commands ###
