"""Add AreaOperativa and modify RecetaIngrediente

Revision ID: 0019
Revises: 0018
Create Date: 2026-05-03 04:59:11.952255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0019'
down_revision: Union[str, None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_operativas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('bodega_consumo_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_consumo_id'], ['operations.bodegas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('area_operativa_bodegas',
    sa.Column('area_operativa_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_operativa_id'], ['operations.areas_operativas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bodega_id'], ['operations.bodegas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_operativa_id', 'bodega_id'),
    schema='operations'
    )
    op.create_table('area_operativa_recetas',
    sa.Column('area_operativa_id', sa.Uuid(), nullable=False),
    sa.Column('receta_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_operativa_id'], ['operations.areas_operativas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receta_id'], ['operations.recetas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_operativa_id', 'receta_id'),
    schema='operations'
    )
    op.create_table('area_operativa_usuarios',
    sa.Column('area_operativa_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_operativa_id'], ['operations.areas_operativas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_operativa_id', 'user_id'),
    schema='operations'
    )
    op.drop_constraint(op.f('receta_ingredientes_bodega_id_fkey'), 'receta_ingredientes', schema='operations', type_='foreignkey')
    op.drop_column('receta_ingredientes', 'bodega_id', schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receta_ingredientes', sa.Column('bodega_id', sa.UUID(), autoincrement=False, nullable=False), schema='operations')
    op.create_foreign_key(op.f('receta_ingredientes_bodega_id_fkey'), 'receta_ingredientes', 'bodegas', ['bodega_id'], ['id'], source_schema='operations', referent_schema='operations')
    op.drop_table('area_operativa_usuarios', schema='operations')
    op.drop_table('area_operativa_recetas', schema='operations')
    op.drop_table('area_operativa_bodegas', schema='operations')
    op.drop_table('areas_operativas', schema='operations')
    # ### end Alembic commands ###
