"""fase2 complete models v2

Revision ID: 0014
Revises: 0013
Create Date: 2026-04-30 18:34:36.892532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: Union[str, None] = '0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_origen_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_destino_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_destino_id'], ['operations.bodegas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bodega_origen_id'], ['operations.bodegas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['operations.productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.add_column('gastos_operativos', sa.Column('bodega_id', sa.UUID(), nullable=True), schema='operations')
    op.add_column('gastos_operativos', sa.Column('descripcion', sa.String(length=500), nullable=True), schema='operations')
    # Explicit Enum creation
    categoria_gasto_enum = postgresql.ENUM('luz', 'agua', 'gas', 'arriendo', 'internet', 'otro', name='categoria_gasto_enum', schema='operations')
    categoria_gasto_enum.create(op.get_bind())

    op.alter_column('gastos_operativos', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('luz', 'agua', 'gas', 'arriendo', 'internet', 'otro', name='categoria_gasto_enum', schema='operations'),
               postgresql_using='categoria::operations.categoria_gasto_enum',
               existing_nullable=False,
               schema='operations')
    op.create_foreign_key(None, 'gastos_operativos', 'bodegas', ['bodega_id'], ['id'], source_schema='operations', referent_schema='operations', ondelete='SET NULL')
    op.add_column('recetas', sa.Column('costo_total', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'), nullable=False), schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recetas', 'costo_total', schema='operations')
    op.alter_column('gastos_operativos', 'categoria',
               existing_type=sa.Enum('LUZ', 'AGUA', 'GAS', 'ARRIENDO', 'INTERNET', 'OTRO', name='categoria_gasto_enum', schema='operations'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               schema='operations')
    op.drop_column('gastos_operativos', 'descripcion', schema='operations')
    op.drop_column('gastos_operativos', 'bodega_id', schema='operations')
    
    # Drop enum
    categoria_gasto_enum = postgresql.ENUM('luz', 'agua', 'gas', 'arriendo', 'internet', 'otro', name='categoria_gasto_enum', schema='operations')
    categoria_gasto_enum.drop(op.get_bind())
    # ### end Alembic commands ###
