"""add_expiration_alert_days

Revision ID: 0021
Revises: 0020
Create Date: 2026-05-08 03:49:42.171783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: Union[str, None] = '0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('dias_alerta_vencimiento', sa.Numeric(precision=5, scale=0), server_default=sa.text('15'), nullable=False), schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'dias_alerta_vencimiento', schema='operations')
    # ### end Alembic commands ###
