"""add models invoices

Revision ID: 0023
Revises: 0022
Create Date: 2026-05-11 12:43:24.722772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0023'
down_revision: Union[str, None] = '0022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_invoice_notifications_type'), 'invoice_notifications', ['type'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_invoice_notifications_user_id'), 'invoice_notifications', ['user_id'], unique=False, schema='operations')
    op.create_table('invoice_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_invoice_settings_key'), 'invoice_settings', ['key'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_invoice_settings_user_id'), 'invoice_settings', ['user_id'], unique=False, schema='operations')
    op.create_table('invoice_webhook_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('events', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_invoice_webhook_endpoints_user_id'), 'invoice_webhook_endpoints', ['user_id'], unique=False, schema='operations')
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('vendor_name', sa.String(length=500), nullable=True),
    sa.Column('vendor_tax_id', sa.String(length=50), nullable=True),
    sa.Column('vendor_fiscal_address', sa.Text(), nullable=True),
    sa.Column('vendor_country', sa.String(length=5), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goods_services_type', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('audit_flags', sa.Text(), nullable=True),
    sa.Column('line_items_data', sa.Text(), nullable=True),
    sa.Column('raw_extracted_data', sa.Text(), nullable=True),
    sa.Column('country_detection_method', sa.String(length=50), nullable=True),
    sa.Column('country_confidence', sa.Float(), nullable=True),
    sa.Column('gemini_tokens_used', sa.Integer(), nullable=False),
    sa.Column('gemini_cost_usd', sa.Float(), nullable=False),
    sa.Column('gemini_model_used', sa.String(length=100), nullable=True),
    sa.Column('gemini_processing_time', sa.Float(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_invoices_filename'), 'invoices', ['filename'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_invoices_user_id'), 'invoices', ['user_id'], unique=False, schema='operations')
    op.drop_table('nota_menciones', schema='operations')
    op.drop_table('plantillas_email', schema='operations')
    op.drop_table('notas', schema='operations')
    op.drop_table('notificaciones_incidencia', schema='operations')
    op.drop_constraint(op.f('productos_sku_key'), 'productos', schema='operations', type_='unique')
    op.drop_column('productos', 'sku', schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='operations')
    op.create_unique_constraint(op.f('productos_sku_key'), 'productos', ['sku'], schema='operations', postgresql_nulls_not_distinct=False)
    op.create_table('notificaciones_incidencia',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('compra_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('resuelto', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['operations.compras.id'], name=op.f('notificaciones_incidencia_compra_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['operations.users.id'], name=op.f('notificaciones_incidencia_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('notificaciones_incidencia_pkey')),
    schema='operations'
    )
    op.create_table('notas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('autor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contenido', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('urgencia', postgresql.ENUM('alta', 'media', 'baja', name='urgencianota', schema='operations'), server_default=sa.text("'media'::operations.urgencianota"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['operations.users.id'], name=op.f('notas_autor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notas_pkey')),
    schema='operations'
    )
    op.create_table('plantillas_email',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('asunto', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('cuerpo', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['operations.users.id'], name=op.f('plantillas_email_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('plantillas_email_pkey')),
    schema='operations'
    )
    op.create_table('nota_menciones',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nota_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['operations.notas.id'], name=op.f('nota_menciones_nota_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], name=op.f('nota_menciones_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nota_menciones_pkey')),
    schema='operations'
    )
    op.drop_index(op.f('ix_operations_invoices_user_id'), table_name='invoices', schema='operations')
    op.drop_index(op.f('ix_operations_invoices_filename'), table_name='invoices', schema='operations')
    op.drop_table('invoices', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_webhook_endpoints_user_id'), table_name='invoice_webhook_endpoints', schema='operations')
    op.drop_table('invoice_webhook_endpoints', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_settings_user_id'), table_name='invoice_settings', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_settings_key'), table_name='invoice_settings', schema='operations')
    op.drop_table('invoice_settings', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_notifications_user_id'), table_name='invoice_notifications', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_notifications_type'), table_name='invoice_notifications', schema='operations')
    op.drop_table('invoice_notifications', schema='operations')
    # ### end Alembic commands ###
