"""add invoices and reports

Revision ID: 0024
Revises: 0023
Create Date: 2026-05-14 13:21:17.374574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0024'
down_revision: Union[str, None] = '0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_gasto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('gastos_operativos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_gasto', sa.Date(), nullable=False),
    sa.Column('es_fijo', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['operations.categorias_gasto.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('invoice_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_invoice_notifications_type'), 'invoice_notifications', ['type'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_invoice_notifications_user_id'), 'invoice_notifications', ['user_id'], unique=False, schema='operations')
    op.create_table('invoice_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_invoice_settings_key'), 'invoice_settings', ['key'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_invoice_settings_user_id'), 'invoice_settings', ['user_id'], unique=False, schema='operations')
    op.create_table('invoice_webhook_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('events', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_invoice_webhook_endpoints_user_id'), 'invoice_webhook_endpoints', ['user_id'], unique=False, schema='operations')
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('vendor_name', sa.String(length=500), nullable=True),
    sa.Column('vendor_tax_id', sa.String(length=50), nullable=True),
    sa.Column('vendor_fiscal_address', sa.Text(), nullable=True),
    sa.Column('vendor_country', sa.String(length=5), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goods_services_type', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('audit_flags', sa.Text(), nullable=True),
    sa.Column('line_items_data', sa.Text(), nullable=True),
    sa.Column('raw_extracted_data', sa.Text(), nullable=True),
    sa.Column('country_detection_method', sa.String(length=50), nullable=True),
    sa.Column('country_confidence', sa.Float(), nullable=True),
    sa.Column('gemini_tokens_used', sa.Integer(), nullable=False),
    sa.Column('gemini_cost_usd', sa.Float(), nullable=False),
    sa.Column('gemini_model_used', sa.String(length=100), nullable=True),
    sa.Column('gemini_processing_time', sa.Float(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['operations.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index(op.f('ix_operations_invoices_filename'), 'invoices', ['filename'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_invoices_user_id'), 'invoices', ['user_id'], unique=False, schema='operations')
    op.create_table('transferencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_origen_id', sa.Uuid(), nullable=False),
    sa.Column('bodega_destino_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_destino_id'], ['operations.bodegas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bodega_origen_id'], ['operations.bodegas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['operations.productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['operations.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.add_column('compra_items', sa.Column('cantidad_pedida', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False), schema='operations')
    op.add_column('compras', sa.Column('proveedor_id', sa.UUID(), nullable=True), schema='operations')
    op.create_foreign_key(None, 'compras', 'proveedores', ['proveedor_id'], ['id'], source_schema='operations', referent_schema='operations', ondelete='SET NULL')
    op.drop_column('compras', 'proveedor', schema='operations')
    op.add_column('productos', sa.Column('proveedor_id', sa.UUID(), nullable=True), schema='operations')
    op.execute("UPDATE operations.productos SET precio_venta = 0.0 WHERE precio_venta IS NULL")
    op.alter_column('productos', 'precio_venta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='operations')
    op.create_foreign_key(None, 'productos', 'proveedores', ['proveedor_id'], ['id'], source_schema='operations', referent_schema='operations', ondelete='SET NULL')
    op.drop_column('productos', 'dias_alerta_vencimiento', schema='operations')
    op.drop_column('productos', 'proveedor', schema='operations')
    op.add_column('proveedores', sa.Column('categoria_principal', sa.String(length=100), nullable=True), schema='operations')
    op.add_column('proveedores', sa.Column('dias_plazo_pago', sa.Integer(), nullable=True), schema='operations')
    op.execute("UPDATE operations.proveedores SET dias_plazo_pago = 0 WHERE dias_plazo_pago IS NULL")
    op.execute("ALTER TABLE operations.proveedores ALTER COLUMN dias_plazo_pago SET NOT NULL")
    op.add_column('proveedores', sa.Column('tiempo_entrega_promedio_dias', sa.Integer(), nullable=True), schema='operations')
    op.add_column('proveedores', sa.Column('activo', sa.Boolean(), nullable=True), schema='operations')
    op.execute("UPDATE operations.proveedores SET activo = true WHERE activo IS NULL")
    op.execute("ALTER TABLE operations.proveedores ALTER COLUMN activo SET NOT NULL")
    op.add_column('proveedores', sa.Column('is_deleted', sa.Boolean(), nullable=True), schema='operations')
    op.execute("UPDATE operations.proveedores SET is_deleted = false WHERE is_deleted IS NULL")
    op.execute("ALTER TABLE operations.proveedores ALTER COLUMN is_deleted SET NOT NULL")
    op.add_column('recetas', sa.Column('costo_total', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'), nullable=False), schema='operations')
    op.execute("CREATE TYPE operations.motivo_merma_enum AS ENUM('vencimiento', 'daño', 'error', 'caducidad', 'exceso', 'mal estado', 'otro')")
    op.execute("ALTER TABLE operations.registros_stock ALTER COLUMN motivo_merma TYPE operations.motivo_merma_enum USING motivo_merma::text::operations.motivo_merma_enum")
    op.alter_column('registros_stock', 'motivo_merma',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('vencimiento', 'daño', 'error', 'caducidad', 'exceso', 'mal estado', 'otro', name='motivo_merma_enum', schema='operations'),
               existing_nullable=True,
               schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE operations.registros_stock ALTER COLUMN motivo_merma TYPE VARCHAR(255) USING motivo_merma::text")
    op.execute("DROP TYPE IF EXISTS operations.motivo_merma_enum")
    op.drop_column('recetas', 'costo_total', schema='operations')
    op.execute("ALTER TABLE operations.proveedores ALTER COLUMN is_deleted DROP NOT NULL")
    op.drop_column('proveedores', 'is_deleted', schema='operations')
    op.execute("ALTER TABLE operations.proveedores ALTER COLUMN activo DROP NOT NULL")
    op.drop_column('proveedores', 'activo', schema='operations')
    op.drop_column('proveedores', 'tiempo_entrega_promedio_dias', schema='operations')
    op.execute("ALTER TABLE operations.proveedores ALTER COLUMN dias_plazo_pago DROP NOT NULL")
    op.drop_column('proveedores', 'dias_plazo_pago', schema='operations')
    op.drop_column('proveedores', 'categoria_principal', schema='operations')
    op.add_column('productos', sa.Column('proveedor', sa.VARCHAR(length=200), autoincrement=False, nullable=True), schema='operations')
    op.add_column('productos', sa.Column('dias_alerta_vencimiento', sa.NUMERIC(precision=5, scale=0), server_default=sa.text('15'), autoincrement=False, nullable=False), schema='operations')
    op.drop_constraint(None, 'productos', schema='operations', type_='foreignkey')
    op.alter_column('productos', 'precio_venta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'),
               schema='operations')
    op.drop_column('productos', 'proveedor_id', schema='operations')
    op.add_column('compras', sa.Column('proveedor', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='operations')
    op.drop_constraint(None, 'compras', schema='operations', type_='foreignkey')
    op.drop_column('compras', 'proveedor_id', schema='operations')
    op.drop_column('compra_items', 'cantidad_pedida', schema='operations')
    op.drop_table('transferencias', schema='operations')
    op.drop_index(op.f('ix_operations_invoices_user_id'), table_name='invoices', schema='operations')
    op.drop_index(op.f('ix_operations_invoices_filename'), table_name='invoices', schema='operations')
    op.drop_table('invoices', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_webhook_endpoints_user_id'), table_name='invoice_webhook_endpoints', schema='operations')
    op.drop_table('invoice_webhook_endpoints', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_settings_user_id'), table_name='invoice_settings', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_settings_key'), table_name='invoice_settings', schema='operations')
    op.drop_table('invoice_settings', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_notifications_user_id'), table_name='invoice_notifications', schema='operations')
    op.drop_index(op.f('ix_operations_invoice_notifications_type'), table_name='invoice_notifications', schema='operations')
    op.drop_table('invoice_notifications', schema='operations')
    op.drop_table('gastos_operativos', schema='operations')
    op.drop_table('categorias_gasto', schema='operations')
    # ### end Alembic commands ###
